name: Build APK Andrew
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Gerar Motor Gradle (Wrapper)
        run: gradle wrapper --gradle-version 8.0

      - name: Dar Permissão ao Instalador
        run: chmod +x gradlew

      - name: Fabricar APK (Build)
        run: ./gradlew assembleDebug --stacktrace

      - name: Entregar APK Pronto
        uses: actions/upload-artifact@v4
        with:
          name: AndrewVIP-Mod
          path: app/build/outputs/apk/debug/*.apk
          
